Log of errors for batch_load_urdb_to_postgres.py (20151028_104936)
